# Generated by Django 2.2.2 on 2019-06-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190616_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='request_type',
            field=models.CharField(choices=[('new product', 'New'), ('reload product', 'Reload')], max_length=100),
        ),
    ]
