# Generated by Django 2.2.2 on 2019-06-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190618_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
            preserve_default=False,
        ),
    ]
