# Generated by Django 2.2.5 on 2019-11-24 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191124_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracker',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
