# Generated by Django 2.2.5 on 2019-11-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_tracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
