# Generated by Django 2.2.2 on 2019-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_remove_transport_location_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='locations',
            field=models.ManyToManyField(to='supply.LocationSupply'),
        ),
    ]
