# Generated by Django 2.2.2 on 2019-06-22 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_request_start_date'),
        ('supply', '0005_transport_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Transport')),
            ],
        ),
    ]
