# Generated by Django 2.2.2 on 2019-06-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_auto_20190618_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='capacity',
            field=models.PositiveIntegerField(default=70),
            preserve_default=False,
        ),
    ]
