# Generated by Django 2.2.2 on 2019-06-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_transport_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='location_assigned',
        ),
    ]
