# Generated by Django 2.2.2 on 2019-06-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_transportorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportorder',
            name='order',
        ),
    ]
