# Generated by Django 2.2.2 on 2019-06-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_request_start_date'),
        ('supply', '0007_remove_transportorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
            preserve_default=False,
        ),
    ]
