# Generated by Django 2.2.2 on 2019-06-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190616_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('request_type', models.CharField(choices=[('new product', 'New'), ('reload product', 'Reload')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Request')),
            ],
        ),
    ]
