# Generated by Django 2.2.2 on 2019-06-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='request',
            name='product',
        ),
    ]
