# Generated by Django 2.2.2 on 2019-06-16 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190616_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Request'),
        ),
    ]
