# Generated by Django 2.2.2 on 2019-06-22 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190618_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 4, 48, 35, 704505, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
