# Generated by Django 2.2.5 on 2019-10-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191019_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
