# Generated by Django 2.2.5 on 2019-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191027_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='request_type',
        ),
        migrations.AddField(
            model_name='product',
            name='request_type',
            field=models.CharField(choices=[('new product', 'New'), ('reload product', 'Reload')], default='new product', max_length=100),
            preserve_default=False,
        ),
    ]
