# Generated by Django 2.2.5 on 2019-10-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191027_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='request_type',
            new_name='product_type',
        ),
    ]
