# Generated by Django 2.2.5 on 2019-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191027_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(default='', upload_to='static'),
            preserve_default=False,
        ),
    ]
